__Numpy__

Numerical Python,written in C and Faster in Execution

GENERAL NOTES:-

# 1.Create Array

# 2.Attributes Of Array

# 3.Access Element Of Array

### a> Indexing:- Accessing single element of array. (view)

    1D: array[index]-> element
    2D: array[row_index]-> return row
        array[row_index][column_index]-> return element
    3D: array[2D_index]-> 2D array
        array[2D_index][row_index]-> return row
        array[2D_index][row_index][column_index]-> return element

### b> Slicing:- Accessing group of Element which are in order (view)
    1D: array[start:end:step]
    2D: array[::,::]
    3D: array[::,::,::]<==>array[2D,row,column]
### c> Fancy Indexing/Advance Slicing:- Accessing Arbitary Element (copy)
    # contain list or ndarray(Numpy array) contain indices
    1D: array[[indices]]
    2D: array[[row],[column]]
    3D: array[[2D],[row],[column]]
### d> Boolean Indexing:- conditon return boolean array which act as  mask to filter. (view)
    Condition: a>10 -> boolean array
    Condition Operator: <,>,==,<=,>=,!=,%=
    Masking on boolean array: a[a>50]-> return value of a-array whoes boolean value id True

NOTE:- 
Python Slicing-> Copy is Created.
Numpy Slicing-> View is Created.
Fancy Indexing-> View is Created.

In [2]:
import numpy as np
a1=np.arange(8)
a2=np.arange(8).reshape(4,2)
a3=np.arange(8).reshape(2,2,2)

#a>Indexing
a3[0]
a3[0][0]
a3[0][0][0]




0

# 4.Iteration Over Numpy Array

## Three ways for Iteration:-
### 1>Python Looping
    for i in a1:-> Iterate over each element
    for i in a2:-> iterate over 1D row
    for i in a3:-> iterate over 2D array
    
### 2>Use nditer()
    it will generate object of flattern array
    
### 3>Use ndenumerator()
    similar to nditer() but also provide indices(position) of value with it.

In [3]:
#python looping
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [4]:
#nditer()    
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7


In [5]:
#ndenumerate
for i in np.ndenumerate(a3):
    print(i)

((0, 0, 0), 0)
((0, 0, 1), 1)
((0, 1, 0), 2)
((0, 1, 1), 3)
((1, 0, 0), 4)
((1, 0, 1), 5)
((1, 1, 0), 6)
((1, 1, 1), 7)


# 5.Delete

### 1>Axis Provided:- Delete given axis indice as given
    1D: no axis is needed 
    2D: Axis-0 refers to as row
        Axis-1 refers as column
    3D: Axis-0 refers to as 2D Array
        Axis-1 refers as row
        Axis-1 refers as column 
### 2>Axis Not provided:- flattern array and then delete


#### 3D array is collection of 2D array

In [6]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### axis-0 will delete 2D array at indice 1

In [7]:
np.delete(a3,[1],axis=0) 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### axis-1 will delete given row from every 2D array

In [8]:
np.delete(a3,[1,2],axis=1) 

array([[[ 0,  1,  2]],

       [[ 9, 10, 11]],

       [[18, 19, 20]]])

#### axis-2 will delete given column from every 2D array

In [9]:
np.delete(a3,[2],axis=2) 

array([[[ 0,  1],
        [ 3,  4],
        [ 6,  7]],

       [[ 9, 10],
        [12, 13],
        [15, 16]],

       [[18, 19],
        [21, 22],
        [24, 25]]])

#### Axis not provided then flattern array and delete from given indices

In [10]:
np.delete(a3,[1,2,11]) 

array([ 0,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26])

# 6.Insert and Replace
##### np.insert(array,indices,value,axis)
    ->copy
    ->insert at given indices
    ->single value or ndarray can be passed
##### np.append(array,value,axis)
    ->copy
    ->add at end only
    ->only ndarray is allowed
##### np.put(array,indices,value)
    ->permanenent (not produce view it will make changes in array directly)
    ->can add only value 
    ->don't give error whatever you do except out of bound
    ->consider array as flattern and act on it but still shape of array dosen't change

## np.insert(array,indices,value,axis)-->copy

### 1>Axis Provided:- Add value to given axis as indice given
    1D: directly add value at given location
    2D: Axis-0 add row with given value or row at given indices
        Axis-1 add column with given value or column at given location
    3D: Axis-0 add 2D Array made from given value or can pass 2d array yourself at given location
        Axis-1 add row with given value or row in all 2D matrices at given indices
        Axis-1 add column with given value or column in all 2D matrices at given location
    3D Sumarise Note:-Axis-0(add 2D array),Axis-1(add row),Axis-0(add column) 
### 2>Axis Not provided:- flattern array and then add


#### axis-0 means adding 2D array in 3D at given indices

In [11]:
import numpy as np
a3=np.arange(27).reshape(3,3,3)
np.insert(a3,[1,3],333,axis=0)

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8]],

       [[333, 333, 333],
        [333, 333, 333],
        [333, 333, 333]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26]],

       [[333, 333, 333],
        [333, 333, 333],
        [333, 333, 333]]])

In [12]:
import numpy as np
add=np.arange(9).reshape(3,3) #2D array
a3=np.arange(27).reshape(3,3,3)
np.insert(a3,[1,3],add,axis=0)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

#### axis-1 means adding row in every 2D array of 3D array at given indices

In [13]:
np.insert(a3,[2],444,axis=1) #single value maek row

array([[[  0,   1,   2],
        [  3,   4,   5],
        [444, 444, 444],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [444, 444, 444],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [444, 444, 444],
        [ 24,  25,  26]]])

In [14]:
np.insert(a3,[2],[2,3,4],axis=1) #pass row

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 2,  3,  4],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [ 2,  3,  4],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [ 2,  3,  4],
        [24, 25, 26]]])

#### axis-2 means adding column in every 2D array of 3D array at given indices

In [15]:
np.insert(a3,[2],2,axis=2) #passing single value making column

array([[[ 0,  1,  2,  2],
        [ 3,  4,  2,  5],
        [ 6,  7,  2,  8]],

       [[ 9, 10,  2, 11],
        [12, 13,  2, 14],
        [15, 16,  2, 17]],

       [[18, 19,  2, 20],
        [21, 22,  2, 23],
        [24, 25,  2, 26]]])

In [16]:
np.insert(a3,[1],[[1],[2],[3]],axis=2) #passing single column

array([[[ 0,  1,  1,  2],
        [ 3,  2,  4,  5],
        [ 6,  3,  7,  8]],

       [[ 9,  1, 10, 11],
        [12,  2, 13, 14],
        [15,  3, 16, 17]],

       [[18,  1, 19, 20],
        [21,  2, 22, 23],
        [24,  3, 25, 26]]])

In [17]:
np.insert(a3,[1],[[1,2],[2,3],[3,4]],axis=2) #passing 2 column

array([[[ 0,  1,  2,  1,  2],
        [ 3,  2,  3,  4,  5],
        [ 6,  3,  4,  7,  8]],

       [[ 9,  1,  2, 10, 11],
        [12,  2,  3, 13, 14],
        [15,  3,  4, 16, 17]],

       [[18,  1,  2, 19, 20],
        [21,  2,  3, 22, 23],
        [24,  3,  4, 25, 26]]])

#### Not passing axis leads to flattern array 

In [18]:
np.insert(a3,10,20000)

array([    0,     1,     2,     3,     4,     5,     6,     7,     8,
           9, 20000,    10,    11,    12,    13,    14,    15,    16,
          17,    18,    19,    20,    21,    22,    23,    24,    25,
          26])

In [19]:
np.append(a3,[[[  9,  10,  11],[999, 999, 999],[ 12,  13,  14]]],axis=0) 

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26]],

       [[  9,  10,  11],
        [999, 999, 999],
        [ 12,  13,  14]]])

In [20]:
np.append(a3,[[[10,10,10],[10,10,10],[10,10,10]],[[10,10,10],[10,10,10],[10,10,10]],[[10,10,10],[10,10,10],[10,10,10]]],axis=1) 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [21]:
np.append(a3,[[[10,10,10],[10,10,10],[10,10,10]],[[10,10,10],[10,10,10],[10,10,10]],[[10,10,10],[10,10,10],[10,10,10]]],axis=2) 

array([[[ 0,  1,  2, 10, 10, 10],
        [ 3,  4,  5, 10, 10, 10],
        [ 6,  7,  8, 10, 10, 10]],

       [[ 9, 10, 11, 10, 10, 10],
        [12, 13, 14, 10, 10, 10],
        [15, 16, 17, 10, 10, 10]],

       [[18, 19, 20, 10, 10, 10],
        [21, 22, 23, 10, 10, 10],
        [24, 25, 26, 10, 10, 10]]])

In [22]:
np.append(a3, [[[10],[10],[10]],[[10],[10],[10]],[[10],[10],[10]]] ,axis=2) 

array([[[ 0,  1,  2, 10],
        [ 3,  4,  5, 10],
        [ 6,  7,  8, 10]],

       [[ 9, 10, 11, 10],
        [12, 13, 14, 10],
        [15, 16, 17, 10]],

       [[18, 19, 20, 10],
        [21, 22, 23, 10],
        [24, 25, 26, 10]]])

In [23]:
# np.put(array,indices,value)-->permanenent (view) 
# it will replace from given position it consider array as flattern and then apply change and reshape array as it is 

In [24]:
np.put(a3,[1,3],[200,300]) 

In [25]:
a3

array([[[  0, 200,   2],
        [300,   4,   5],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26]]])

In [26]:
np.put(a3,[1],[500,300]) #don't give error xd except out of bound

In [27]:
a3

array([[[  0, 500,   2],
        [300,   4,   5],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26]]])

# 7.Sorting
#### np.sort(array,kind,axis,order)
    kind->'quicksort','mergesort','heapsort'
    axis->0,1,2

#### Note
    here meaning of axis change it is not within axis it is along axis
    generally  in 3D axis 2 is column but here sorting is happen between diferent column i.e along row row is sorted
    similarly axis 1 is row but here sorting is happen between diferent row i.e column wise sorting happen
    if axis=0 means element at 1,1 in 2d compare with 1,1 of another 2D in 3D
    
    for (3,2) array and axis 1 
    (0,0) compared with (0,1) (1,0) comapared with (1,1) 2,0 compared with (2,1)
    i.e axis1 is changing are compared i.e rows are compared
    
    for (3,2) array and axis 0
    (0,0) compared with (1,0) and (2,0)  
    (0,1) compared with (1,1) and (2,1)
    (0,2) compared with (1,2) and (2,2)
    i.e axis 0 is changing and are compared i.e columns are being compared

In [28]:
a3=np.random.randint(61,109,size=(4,3,2))
a3

array([[[105,  99],
        [106,  83],
        [ 95, 103]],

       [[ 83,  73],
        [ 76, 105],
        [ 85,  68]],

       [[ 96,  68],
        [ 77,  95],
        [105,  63]],

       [[ 87,  97],
        [ 81, 102],
        [ 91,  82]]])

In [29]:
np.sort(a3,axis=1) #axis 1 is kept changing i.e column wise

array([[[ 95,  83],
        [105,  99],
        [106, 103]],

       [[ 76,  68],
        [ 83,  73],
        [ 85, 105]],

       [[ 77,  63],
        [ 96,  68],
        [105,  95]],

       [[ 81,  82],
        [ 87,  97],
        [ 91, 102]]])

In [30]:
np.sort(a3,axis=2) #axis 2 is kept changing i.e row wise

array([[[ 99, 105],
        [ 83, 106],
        [ 95, 103]],

       [[ 73,  83],
        [ 76, 105],
        [ 68,  85]],

       [[ 68,  96],
        [ 77,  95],
        [ 63, 105]],

       [[ 87,  97],
        [ 81, 102],
        [ 82,  91]]])

In [31]:
np.sort(a3,axis=0) #axis 0 is kept changing i.e element of 2D array wise

array([[[ 83,  68],
        [ 76,  83],
        [ 85,  63]],

       [[ 87,  73],
        [ 77,  95],
        [ 91,  68]],

       [[ 96,  97],
        [ 81, 102],
        [ 95,  82]],

       [[105,  99],
        [106, 105],
        [105, 103]]])

# 8.Serching
#### np.where(condition)
    ->return indices where condition mask is True
#### np.where(condition,if,else)
    ->replaced new copy of array 
#### a[condition on a]  
    ->return value where condition mask is True
#### np.isin(array,list_to_search)
    ->return boolean array


#### Get indices of array where condition is True

In [32]:
np.where(a2>2)

(array([1, 2, 2, 3, 3], dtype=int64), array([1, 0, 1, 0, 1], dtype=int64))

#### Make indices recevied from np.where() as mask to return value

In [33]:
a2[np.where(a2>2)]

array([3, 4, 5, 6, 7])

#### Apply IF-ELSE with np.where()

In [34]:
np.where(a2==2,000,12)

array([[12, 12],
       [ 0, 12],
       [12, 12],
       [12, 12]])

#### Another way for Conditional Selection Using Masking

In [35]:
a2[a2>2]

array([3, 4, 5, 6, 7])

#### Effecient Way of searching multiple element using np.isin() which return Boolean Array as mask

In [36]:
np.isin(a2,[1,2,3,4])

array([[False,  True],
       [ True,  True],
       [ True, False],
       [False, False]])

#### Using np.isin() boolean mask to select value

In [37]:
a2[np.isin(a2,[1,2,3,4])]

array([1, 2, 3, 4])

# 9.Joining
#### np.concatenate(array,axis,out,dtype)
    ->join the sequence of ndarray along the axis
    ->dimention of both array should be same
    ->except concatenation axis size of other axis size should be same
    ->dimention of resultant array don't change(1D+1D=1D,2D+2D=2D)
    ->size of other axis is same except concatenation axis which should be sumed ( axis=0 (2,3,4)+(5,3,4)->(4,3,4) )
    ->out:- contain ndarray of that type
    ->axis-0:-concatinate verically along row 
    ->axis-1:- concatinate horizontally along column
    ->adding existing array(adding by going one step inside)
#### np.stack(array,axis,out)
    ->join the sequence of array along new axis
    ->dimention and shape of both array should be same
    ->resultant dimention of array changes by 1(1D+1D=2D,2D+2D=3D,4D+4D=5D)
    ->size of chosen axis will add 2 if 2 array are given,size of chosen axis will add 3 if 3 array are given(axis-1: (2,3,4)+(2,3,4)->(2,2,3,4))
    ->axis-0:-concatinate verically along row 
    ->axis-1:- concatinate horizontally along column
    ->create new array when joining(adding by staying one step outside)

#### np.vstack(array,out)->axis-0 
#### np.hstack(array,out)->axis-1
#### np.dstack(array,out)->axis-2 

    

In [54]:
a_21=np.full((2,2,2),0)
a_22=np.full((2,2,2),1)
a_23=np.full((2,2,2),2)

In [39]:
a_21=np.full((2,2),0)
a_22=np.full((2,2),1)
a_23=np.full((2,2),2)


In [40]:
np.concatenate((a_21,a_22),axis=0) 

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1]])

In [41]:
np.concatenate((a_21,a_22),axis=1) 

array([[0, 0, 1, 1],
       [0, 0, 1, 1]])

In [55]:
np.concatenate((a_21,a_22),axis=2) 

array([[[0, 0, 1, 1],
        [0, 0, 1, 1]],

       [[0, 0, 1, 1],
        [0, 0, 1, 1]]])

In [43]:
np.stack((a_21,a_22),axis=0)

array([[[0, 0],
        [0, 0]],

       [[1, 1],
        [1, 1]]])

In [44]:
np.stack((a_21,a_22),axis=1)

array([[[0, 0],
        [1, 1]],

       [[0, 0],
        [1, 1]]])

In [45]:
np.stack((a_21,a_22),axis=2)

array([[[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]]])

# 10.Spliting
#### np.split(array,indices_or_section,axis)
    ->size of axis will be splited according to indices or section provided
#### np.array_split(array,indices_or_section,axis)
    ->similar to np.split() but error don't occure while spliting uneven 

#### 1>Based on Indices
    if indices is provided then sub array can be of different shape
#### 2>Based on Section
    if section is provided then sub-array should be of equal shape else give error

In [46]:
a=np.random.randint(10,100,(6,4))
a

array([[90, 68, 32, 14],
       [32, 71, 37, 43],
       [97, 84, 75, 47],
       [46, 19, 94, 66],
       [53, 71, 86, 77],
       [72, 19, 46, 74]])

Axis-0 split array row wise by Indices

In [47]:
print("Before Split Shape Of Array:- ",a.shape)
x=np.split(a,[1,2],axis=0)
print("After Split Shape Of Arrays:- ",[i.shape for i in x])
x

Before Split Shape Of Array:-  (6, 4)
After Split Shape Of Arrays:-  [(1, 4), (1, 4), (4, 4)]


[array([[90, 68, 32, 14]]),
 array([[32, 71, 37, 43]]),
 array([[97, 84, 75, 47],
        [46, 19, 94, 66],
        [53, 71, 86, 77],
        [72, 19, 46, 74]])]

Axis-1 split array column wise By indices

In [48]:
print("Before Split Shape Of Array:- ",a.shape)
x=np.split(a,[1,2],axis=1)
print("After Split Shape Of Arrays:- ",[i.shape for i in x])
x

Before Split Shape Of Array:-  (6, 4)
After Split Shape Of Arrays:-  [(6, 1), (6, 1), (6, 2)]


[array([[90],
        [32],
        [97],
        [46],
        [53],
        [72]]),
 array([[68],
        [71],
        [84],
        [19],
        [71],
        [19]]),
 array([[32, 14],
        [37, 43],
        [75, 47],
        [94, 66],
        [86, 77],
        [46, 74]])]

Axis-0 split array row wise by section

In [49]:
print("Before Split Shape Of Array:- ",a.shape)
x=np.split(a,2,axis=0)
print("After Split Shape Of Arrays:- ",[i.shape for i in x])
x

Before Split Shape Of Array:-  (6, 4)
After Split Shape Of Arrays:-  [(3, 4), (3, 4)]


[array([[90, 68, 32, 14],
        [32, 71, 37, 43],
        [97, 84, 75, 47]]),
 array([[46, 19, 94, 66],
        [53, 71, 86, 77],
        [72, 19, 46, 74]])]

Axis-1 split array column wise By Section

In [50]:
print("Before Split Shape Of Array:- ",a.shape)
x=np.split(a,2,axis=1)
print("After Split Shape Of Arrays:- ",[i.shape for i in x])
x

Before Split Shape Of Array:-  (6, 4)
After Split Shape Of Arrays:-  [(6, 2), (6, 2)]


[array([[90, 68],
        [32, 71],
        [97, 84],
        [46, 19],
        [53, 71],
        [72, 19]]),
 array([[32, 14],
        [37, 43],
        [75, 47],
        [94, 66],
        [86, 77],
        [46, 74]])]

In [51]:
a=np.random.randint(10,100,(5,3))
a

array([[28, 55, 86],
       [40, 87, 28],
       [40, 23, 53],
       [16, 51, 73],
       [69, 61, 82]])

#### Section with unequal division 

In [52]:
print("Before Split Shape Of Array:- ",a.shape)
x=np.split(a,2,axis=0)
print("After Split Shape Of Arrays:- ",[i.shape for i in x])
x

Before Split Shape Of Array:-  (5, 3)


ValueError: array split does not result in an equal division

#### Section with unequal division using np.array_split()

In [53]:
print("Before Split Shape Of Array:- ",a.shape)
x=np.array_split(a,2,axis=0)
print("After Split Shape Of Arrays:- ",[i.shape for i in x])
x

Before Split Shape Of Array:-  (5, 3)
After Split Shape Of Arrays:-  [(3, 3), (2, 3)]


[array([[28, 55, 86],
        [40, 87, 28],
        [40, 23, 53]]),
 array([[16, 51, 73],
        [69, 61, 82]])]

# 11.Array Manupulation
#### np.reshape(array,shape,order)
    ->use to change shape withoud changing data
    ->shape must be in form of tuple
    ->size of shape should match with input array 
    ->it is both library level function and object level function
    ->it will give view
    ->order='C'-Column by Column,'F'-Row by Row

#### ndarray.flattern(order)
    ->convert nD array to 1D
    ->order='C','F'
    ->it will return copy 
    ->it have only object level method

#### np.ravel()
    ->similar to flattern
    ->convert nD to 1D
    ->it have both library level method and object level method
    ->It return view
#### np.transpose(array,axes=(1,0))
    ->column become row and row become column
    ->change axis i.e row act as column and column act as row
    ->axes is use to mention which axis use where
    ->axes=(1,0) axis1 act as axis0 and axis0 act as axis1
    ->axes=(1,2,0) axis1 act as axis0 , axis2 act as axis1 , axis0 act as axis2. 
    -> act as libary level,object level and attribute
    ->this flip along diagonal xd
    ->(0,1)<==>(1,0) transpose conversion
#### np.flip(array,axis)
    ->flip around axis
    ->if axis not given then vertical and horizontal flipping along axis
    ->only library level function

#### Reshape as object method

In [58]:
np.arange(27).reshape((3,3,3),order='F')

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

#### Reshape as library level method

In [59]:
a=np.arange(27)
np.reshape(a,(3,3,3),order='F')

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

#### Flattern

In [64]:
a=a.reshape((3,3,3))
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [67]:
a.flatten(order='C') #default 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [68]:
a.flatten(order='F')

array([ 0,  9, 18,  3, 12, 21,  6, 15, 24,  1, 10, 19,  4, 13, 22,  7, 16,
       25,  2, 11, 20,  5, 14, 23,  8, 17, 26])

#### Ravel use as object 

In [75]:
a.ravel(order=('C'))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [76]:
np.ravel(a,order=('F'))

array([ 0,  9, 18,  3, 12, 21,  6, 15, 24,  1, 10, 19,  4, 13, 22,  7, 16,
       25,  2, 11, 20,  5, 14, 23,  8, 17, 26])

NOte:-Ravel is simlar to Flattern just difference is ravel produce view and flattern produce copy

#### Transpose

In [93]:
import numpy as np
a3=np.random.randint(0,1000,(3,3,3))
a2=np.random.randint(0,1000,(5,3))

In [94]:
np.transpose(a2,axes=(1,0))

array([[493, 932, 926, 101, 109],
       [804, 540, 117, 248, 532],
       [805, 960, 821,  92,  71]])

In [95]:
np.transpose(a3,axes=(1,2,0))

array([[[844, 675, 103],
        [ 99, 496, 555],
        [ 69, 718, 859]],

       [[392, 888, 536],
        [656, 842, 471],
        [395, 612, 396]],

       [[578, 828, 175],
        [407, 750, 952],
        [  8, 965, 993]]])

In [96]:
a2.transpose()

array([[493, 932, 926, 101, 109],
       [804, 540, 117, 248, 532],
       [805, 960, 821,  92,  71]])

In [97]:
a2.T

array([[493, 932, 926, 101, 109],
       [804, 540, 117, 248, 532],
       [805, 960, 821,  92,  71]])

#### Flip

In [98]:
np.flip(a2,axis=1)

array([[805, 804, 493],
       [960, 540, 932],
       [821, 117, 926],
       [ 92, 248, 101],
       [ 71, 532, 109]])

In [99]:
np.flip(a2,axis=0)

array([[109, 532,  71],
       [101, 248,  92],
       [926, 117, 821],
       [932, 540, 960],
       [493, 804, 805]])

# 12.Unique
#### np.unique(array,return_index,return_counts,axis)
    ->return sorted array
    ->return count of unique element
    ->return indices of unique value

In [3]:
import numpy as np
x=np.random.randint(10,30,(40))

In [4]:
x

array([25, 11, 28, 12, 17, 26, 24, 22, 11, 24, 25, 17, 21, 20, 12, 25, 27,
       26, 12, 28, 14, 24, 15, 12, 29, 24, 24, 15, 18, 22, 22, 21, 11, 10,
       22, 21, 10, 28, 23, 25])

In [20]:
unique,indices,count=np.unique(x,return_index=True,return_counts=True)
np.unique(x,return_index=True,return_counts=True)

(array([10, 11, 12, 14, 15, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([33,  1,  3, 20, 22,  4, 28, 13, 12,  7, 38,  6,  0,  5, 16,  2, 24],
       dtype=int64),
 array([2, 3, 4, 1, 2, 2, 1, 1, 3, 4, 1, 5, 4, 2, 1, 3, 1], dtype=int64))

In [23]:
x=x.reshape(20,2)

In [28]:
x

array([[25, 11],
       [28, 12],
       [17, 26],
       [24, 22],
       [11, 24],
       [25, 17],
       [21, 20],
       [12, 25],
       [27, 26],
       [12, 28],
       [14, 24],
       [15, 12],
       [29, 24],
       [24, 15],
       [18, 22],
       [22, 21],
       [11, 10],
       [22, 21],
       [10, 28],
       [23, 25]])

In [35]:
np.unique(x,axis=0,return_counts=True) #row wise consider as 1 element

(array([[10, 28],
        [11, 10],
        [11, 24],
        [12, 25],
        [12, 28],
        [14, 24],
        [15, 12],
        [17, 26],
        [18, 22],
        [21, 20],
        [22, 21],
        [23, 25],
        [24, 15],
        [24, 22],
        [25, 11],
        [25, 17],
        [27, 26],
        [28, 12],
        [29, 24]]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=int64))

In [36]:
np.unique(x,axis=1,return_counts=True) #column consider as 1 element

(array([[11, 25],
        [12, 28],
        [26, 17],
        [22, 24],
        [24, 11],
        [17, 25],
        [20, 21],
        [25, 12],
        [26, 27],
        [28, 12],
        [24, 14],
        [12, 15],
        [24, 29],
        [15, 24],
        [22, 18],
        [21, 22],
        [10, 11],
        [21, 22],
        [28, 10],
        [25, 23]]),
 array([1, 1], dtype=int64))